In [6]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
sentences=['the glass of milk',
'the glass of juice',
'the cup of tea',
'I am a good boy',
'I am a good developer',
'understanding the meaning of words is important','your videos are good',]

In [9]:
#   Defining the vocabulary size
voc_size=10000

In [13]:
#One Hot Representation
one_hot_repr=[one_hot(word, voc_size) for word in sentences]
one_hot_repr

[[7064, 5418, 9343, 6325],
 [7064, 5418, 9343, 4981],
 [7064, 6179, 9343, 3392],
 [2954, 1743, 9416, 8669, 5481],
 [2954, 1743, 9416, 8669, 2176],
 [3382, 7064, 1855, 9343, 2343, 1657, 3393],
 [1731, 5308, 8433, 8669]]

In [15]:
#Word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [ ]:
sentence_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sentence_length)
print(embedded_docs)


[[   0    0    0    0 7064 5418 9343 6325]
 [   0    0    0    0 7064 5418 9343 4981]
 [   0    0    0    0 7064 6179 9343 3392]
 [   0    0    0 2954 1743 9416 8669 5481]
 [   0    0    0 2954 1743 9416 8669 2176]
 [   0 3382 7064 1855 9343 2343 1657 3393]
 [   0    0    0    0 1731 5308 8433 8669]]


In [20]:
#Feature representation
dimensions=10
model=Sequential()
model.add(Embedding(voc_size,dimensions,input_length=sentence_length))
model.compile('adam','mse')

c:\Users\KIIT0001\Desktop\Python Skillbuilding\DL\rnn_project\venv\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [21]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step


array([[[ 4.98022102e-02, -1.80566199e-02,  3.51969115e-02,
         -1.03842616e-02, -4.87321503e-02, -3.33402902e-02,
         -3.38599905e-02, -2.32932698e-02, -9.38723236e-03,
         -1.68689713e-02],
        [ 4.98022102e-02, -1.80566199e-02,  3.51969115e-02,
         -1.03842616e-02, -4.87321503e-02, -3.33402902e-02,
         -3.38599905e-02, -2.32932698e-02, -9.38723236e-03,
         -1.68689713e-02],
        [ 4.98022102e-02, -1.80566199e-02,  3.51969115e-02,
         -1.03842616e-02, -4.87321503e-02, -3.33402902e-02,
         -3.38599905e-02, -2.32932698e-02, -9.38723236e-03,
         -1.68689713e-02],
        [ 4.98022102e-02, -1.80566199e-02,  3.51969115e-02,
         -1.03842616e-02, -4.87321503e-02, -3.33402902e-02,
         -3.38599905e-02, -2.32932698e-02, -9.38723236e-03,
         -1.68689713e-02],
        [ 6.82948902e-03,  3.33133079e-02,  4.58029546e-02,
          4.06886004e-02, -3.42367887e-02,  2.74587385e-02,
         -6.90151006e-04,  4.56655659e-02, -2.738386

In [23]:
embedded_docs[0]

array([   0,    0,    0,    0, 7064, 5418, 9343, 6325], dtype=int32)